-- CAL DISCOUNT
SET SERVEROUTPUT ON 
DECLARE
PRODUCT_NAME CHAR(6) :=&PRODUCT_NAME;
PRICE NUMBER :=&PRICE;
QUANTITY NUMBER :=&QUANTITY;
DISCOUNT NUMBER :=10;
DISCOUNTPRICE NUMBER;
BEGIN
    DISCOUNTPRICE := (PRICE * DISCOUNT)/100;
    
    DBMS_OUTPUT.PUT_LINE(' DISCOUNTPRICE ='||DISCOUNTPRICE);

END;
/