

INSERT INTO EMP (EMPNO, ENAME, JOB, SAL, DEPTNO)
VALUES (9001, 'JOHN', 'MANAGER', 60000, 10);


CREATE OR REPLACE TRIGGER restrict_salary
BEFORE INSERT OR UPDATE
ON EMP
FOR EACH ROW
BEGIN
    IF :NEW.SAL > 50000 THEN
        RAISE_APPLICATION_ERROR(-20002, 'ERROR: Salary cannot be greater than Rs 50000!');
    END IF;
END restrict_salary;
/