-- CAL SQARE & CUBE
SET SERVEROUTPUT ON
DECLARE
NUM NUMBER:=20;
SQUARE NUMBER;
CUBE NUMBER;
BEGIN
    SQUARE := NUM * NUM;
    CUBE:= NUM * NUM * NUM;
    DBMS_OUTPUT.PUT_LINE('SQUARE='||SQUARE);
    DBMS_OUTPUT.PUT_LINE('CUBE='||CUBE);
END;
/